# setting up docker image --> coming soon
stages:
  - build
  - test
  - analyze
build:
  stage: build
  tags:
    - linux
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    # install build toolkit ( libasan5 for  adress sanitizer, gcovr ggcov lcov for code coverage)
    - apt update && apt -y install make libasan5 gcc gcovr lcov
    # We will install latest CMake
    - apt purge --auto-remove cmake
    - mkdir -p /opt/cmake
    - curl -s "https://cmake.org/files/v3.19/cmake-3.19.4-Linux-x86_64.tar.gz" | tar --strip-components=1 -xz -C /opt/cmake
    - ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
    # install cmocka
    - wget http://git.cryptomilk.org/projects/cmocka.git/snapshot/master.tar.gz
    - tar -xvf master.tar.gz
    - cd master  
    - mkdir build 
    - cd build   
    - cmake ..
    - make all install
    - cd ..      
    - cd ..
    - ldconfig
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
  # artifacts parameter informs about the files and folders that must be kept after the job is done 
  artifacts:
      expire_in: 10 mins
      paths:
      - build/
      - bin/
test:
  stage: test
  tags:
    - linux
  script:
    - cd build && ctest
  dependencies:
    - build
  artifacts:
    expire_in: 10 mins
    paths:
      - build/
      - bin/

analyze:
  stage: analyze
  tags:
    - linux
  script:
    - cd build && make vector_coverage
  dependencies:
    - test
  artifacts:
      expire_in: 1 week
      paths:
        - build/vector_coverage/*
        - build/test_vector_logs.txt
