variables:
  BUILD_IMAGES_PROJECT: gitlabciintrogroup/gitlabciimages
  FEDORA_BUILD: buildenv-fedora
  UBUNTU_BUILD: buildenv-ubuntu

before_script:
 - echo "job started by ${GITLAB_USER_NAME}"

stages:
  - build

fedora-build:
  image: $CI_REGISTRY/$BUILD_IMAGES_PROJECT:$FEDORA_BUILD
  stage: build
  script:
    - cmake --version
    - mkdir buildf
    - cd buildf
    - cmake ..
    - make
    - cd tests
    - make vector_coverage
  tags:
  - shared
  except:
  - tags
  artifacts:
    expire_in: 1 week
    paths:
      - buildf
